name: GitHub Action Demo
on: [push]
jobs:
  Exploring: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - run: echo "This Action was triggered by a ${{ github.event_name }} event"
  
  Building:
    needs: Exploring
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the project ${{ secrets.MY_SECRET}}"
      - run: echo "Build complete ${{ vars.testvariable }}"
  
  Checkout:
    needs: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "Checking out the code"
